### ISSUE TITLE
Sharing subscriptions

### ISSUE THREAD

**Issue by ncreated** [icanzilb/RxTimelane#14]
Hello 👋. I took this wonderful tool to play with it a bit. I spotted the problem (?) with instrumenting multiple subscriptions to the same stream. 

### The problem

When I put the `.lane()` operator close to the stream definition and subscribe the `stream` two times:
```swift
let stream = Observable<String>.worker(duration: 2.0)
    .lane("Will Complete", filter: [.subscription])

stream
    .subscribe()
    .disposed(by: bag)

stream
    .subscribe()
    .disposed(by: bag)
```
this is what happens:

![May-22-2020 15-44-02](https://user-images.githubusercontent.com/2358722/82674710-055e5980-9c44-11ea-95d6-27c02a0bf7fb.gif)

The more subscriptions I do, the more spans disappear randomly in the instrument.

### The solution 🤔 

⚙️  I'm wondering if there is any solution to this problem. Given that `RxTimelane` tracks subscription by sharing the `Timelane.Subscription` object between `Observable` callbacks, this problem would require a collection of `[Timelane.Subscription]` being shared. However, there's no way to identify which subscription a given callback is called for, as we cannot "identify" the stream instance (do we?).

My consideration comes from the fact that I'm working on a similar problem now, and I'm looking for a solution. I hoped to find a clue in `RxTimelane`, but I found my own problem here instead 🙂. I'd be happy to hear your thought on this @icanzilb - this might help me as well.

**Comment by icanzilb** [comment]
@ncreated That's an interesting issue :) on one side - you would expect to see two lanes because you create two subscriptions, but on the other - you have just one lane operator and all bars in that lane have the same name so they are identical ... I know I tested with shared subscriptions in the past but to be honest I haven't really tried your case where you have a non-shared observable that is being subscribed multiple times ... I'm not even sure how Timelane should behave in that case ... like what would you expect to see a bar for each of the active subscriptions? Or something else?

**Comment by ncreated** [comment]
@icanzilb I’m asking myself exactly the same questions in the tool I’m working on.

I think that what would be most valuable to the user is to see:
- number of subscriptions,
- their exact lifespan (start and end).

That would help users to, for example, notice the need of sharing the subscription or to see that their subscription count is crazy high.

However, I think the second point is impossible to handle, as the subscription has no „identity” we could refer to in `onDispose {}`.

That’s why I only managed to fulfill the first point in my tool. I’m updating the span’s name by adding `#count` to its name (i.e. `#3`). The span starts at the first `onSubscribe` and ends with the last `onDispose`.

I’m wondering  what’s your take on this, and how this sould be handled? 

I don’t think this should be ignored and only one span should be drawn, as we have only one `lane()` definition - that might be misleading and won’t help to spot the subscription sharing need.

**Comment by icanzilb** [comment]
Check out https://github.com/icanzilb/RxTimelane/releases/tag/1.0.8 - I believe this should fix the issue. In this release RxTimelane creates a core subscription each time there is a new observer so now each subscription (for each observer) completes correctly and does not interfere with other subscriptions for the same lane operator.

https://github.com/icanzilb/RxTimelane/blob/master/Tests/RxTimelaneTests/RxTimelaneTests.swift#L217-L226

**Comment by ncreated** [comment]
Hey @icanzilb 👋. I'm afraid this introduces a serious bug 😬🐛 , as events are no longer passed through the instrumented stream. See this example:

```swift
Observable
    .just("hello")
    .lane("lane")
    .do(onNext: { print("⭐️ \($0)") })
    .subscribe()
    .disposed(by: bag)
```

It watches the stream subscription, but doesn't `print` any message:

<img width="1521" alt="Screenshot 2020-05-25 at 11 57 03" src="https://user-images.githubusercontent.com/2358722/82802420-278feb80-9e7f-11ea-872f-7916c3d7ce48.png">

Please confirm 🙏.

**Comment by icanzilb** [comment]
Arrr! I knew it was too good to be true :))) But I feel I'm almost there - let me have another look today 😁

**Comment by ncreated** [comment]
Great 👌. Sorry for implicitly breaking your stuff - this approach also passed tests on my side, but made the real app break epically. I'm adding events propagation tests on my side, you may want do do it as well 😄.

**Comment by icanzilb** [comment]
Oh yeah, I can see how timelane's test suite doesn't really test that 😂 good stuff - thank you so much for the detailed feedback 🚀

**Comment by ncreated** [comment]
Btw, I had a problem with running the `RxTimelaneExample` app right after `git clone` - I think the  setup was broken in https://github.com/icanzilb/RxTimelane/commit/e550be1741c81a0a1f3b3b00e931efd2e1f13927. I had to fix it manually. You may want to also fix this 🙂.

**Comment by icanzilb** [comment]
@ncreated would you give https://github.com/icanzilb/RxTimelane/releases/tag/1.0.9 a try? I think this time I got all bases covered 😅

**Comment by ncreated** [comment]
@icanzilb I used the same approach for my tool, and it works even for a non-trivial stream example with flat maps, combines, subjects etc 🚀.

I checked also the `RxTimelaneExample` project - it works perfectly well 👌, although you might want to bump the `RxTimelane` to `1.0.9` [in `Package.resolved`](https://github.com/icanzilb/RxTimelane/blob/39227ffa73d96986b7184c06b0f2c1734265b8a1/RxTimelaneExample/RxTimelane.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved#L19) 🙂.

Anyway, thanks for this 🍻! I wouldn't came up with a solution that fast, kudos to you 💪!

**Comment by icanzilb** [comment]
Pure coincidence that I couldn't sleep on Sunday night so I "had" some free time to look into this :) Thanks for your input, it really helped
