### ISSUE TITLE
Update RxTimelane to work with RxSwift 6.0

### ISSUE THREAD

**Issue by danielt1263** [icanzilb/RxTimelane#18]
RxSwift 6.0 was released Jan 1. When can we expect an update to RxTimelane?

**Comment by icanzilb** [comment]
That's a great point @danielt1263 - do you want to try opening a PR for this? I don't think it'll be much hassle to.

**Comment by icanzilb** [comment]
This has been addressed: https://twitter.com/icanzilb/status/1350388788510523394
