### ISSUE TITLE
Add carthage build to CI

### ISSUE THREAD

**Issue by icanzilb** [icanzilb/RxTimelane#5]
I'd like the CI to build the Carthage framework to make sure there are no breaking changes.

It seems that to do this we need a custom docker image with installed carthage though 🤔

**Comment by icanzilb** [comment]
Will copy the TimelaneCombine Carthage action, once we re-structure this repo. @KarimEbrahemAbdelaziz - how are you, still up for doing the re-structure for this repo? If you're busy just let me know, I can have a look myself later on.

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb I am fine Marin, How are you? 😊
Yup, still up for it. Just was busy last days. 
Wait for my PR today 💪🔥

**Comment by KarimEbrahemAbdelaziz** [comment]
@icanzilb Evening Marin,
Please check this PR #6 I did re-structure for this repo as `TimelaneCombine` structure.
Made with love for Timelane ❤️🔥

**Comment by icanzilb** [comment]
https://github.com/icanzilb/RxTimelane/pull/7
